### ISSUE TITLE
Bot url upload limit

### ISSUE THREAD

**Issue by ibi01** [Amaimersion/yandex-disk-telegram-bot#4]
# Question

## Summary

What is the bot url upload limit , I am not able to upload 1gb file in yandex disk

**Comment by Amaimersion** [comment]
Hello!

Upload limit is **20 MB**. You can type `/help` to see this information (`Maximum size of every upload (except URL) is 20 MB.`).

It is Telegram limit, not Yandex.Disk. I will try to bypass this limit somehow in the future, but at the moment it is as it is. See this for more #3

**Comment by ibi01** [comment]
I just want to know upload limit in url upload.
You said limit is 20mb except url
Than what is url upload limit
Please reply soon

**Comment by Amaimersion** [comment]
There is no limit for uploading by URL

**Comment by ibi01** [comment]
I have got this error
Please help

**Comment by Amaimersion** [comment]
What error?

**Comment by ibi01** [comment]
This error -

 I can't track operation status of this anymore. Perform manual checking.

Please see screenshot mentioned above

**Comment by Amaimersion** [comment]
There is no any screenshots above. Anyway, it is not an error.

` I can't track operation status of this anymore. Perform manual checking.` means your file takes a long time to be completely uploaded on Yandex.Disk, this upload time much more than bot tracking time. i.e., uploading process is fine, but bot will not track this uploading because it takes a long time. You have to manually open Yandex.Disk and check it by yourself. Most probably you will see your file, or it will be available later (when Yandex will finish the download).

**Comment by ibi01** [comment]
Thanks for your help 🙏
Awesome work bro...

Thanks again 🔥🔥🔥
